# Generated by Django 5.0.6 on 2024-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dgz5gpe5z/image/upload/v1716118492/media/images/profile_dec7sg.jpg', upload_to='images/'),
        ),
    ]
