# Generated by Django 3.2.25 on 2024-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dgz5gpe5z/image/upload/v1717022252/media/images/Screenshot_2024-05-29_212019_h2nbja.png', upload_to='images/'),
        ),
    ]
