# Generated by Django 3.2.25 on 2024-05-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/Screenshot_2024-05-29_212019_h2nbja.png', upload_to='images/'),
        ),
    ]
