# Generated by Django 3.2.25 on 2024-04-30 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snaps', '0003_remove_snap_image_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapcomments', to='snaps.snap')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
