# Generated by Django 3.2.25 on 2024-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='snapcomment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapcomment',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapcomment',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snapcomment',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
