# Generated by Django 5.0.6 on 2024-05-11 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snaps', '0003_remove_snap_image_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapdislikes', to='snaps.snap')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('owner', 'snap')},
            },
        ),
    ]
