# Generated by Django 3.2.25 on 2024-04-30 13:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0003_remove_snap_image_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snaplikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='SnapLike',
        ),
    ]
