# Generated by Django 3.2.25 on 2024-04-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_snap_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snap',
            name='image_filter',
        ),
    ]
