# Generated by Django 3.2.25 on 2024-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0003_remove_snap_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='snap',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snap',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='snap',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snap',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snap',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
